behaviors:
    MotionCaptureRNN:
        trainer_type: ppo
        hyperparameters:
            batch_size: 128
            beta: 5.0e-3
            buffer_size: 100
            learning_rate: 0.5e-4
            epsilon: 0.2
            lambd: 0.95
            learning_rate_schedule: linear
            num_epoch: 3
        network_settings:
            hidden_units: 256
            normalize: false
            num_layers: 2
            memory:
                memory_size: 128
                sequence_length: 128
        reward_signals:
            extrinsic:
                strength: 1.0
                gamma: 0.99

        max_steps: 50000000
        time_horizon: 64
        summary_freq: 1000